### PR TITLE
feat: move minimap to suite logo

### PR DESCRIPTION
**Pull request by nastyastavitskaya**
## Summary

- Based on user feedback, it was decided to move the minimap to the top of the nav bar and open on suite logo hover. 
- Design spec: https://www.figma.com/design/Zua9XIORG5fXRnrs2FZkfJ/Overview-Map-post-GA-Improvements?node-id=5317-12165&m=dev
- **Important**: should only be merged after https://github.com/mParticle/aquarium/pull/367. 

## Testing Plan

- [x] Was this tested locally? If not, explain why.
- Run `Global Navigation` stories (mp or cortex) confirm minimap now opens on top nav logo hover.
- Run `Global Navigation: MP With Nav Switcher Tour` on Suite Logo hover you''ll get the minimap, on click the Tour popover.
Screenshot 2024-08-13 at 3 10 54 PM

## Reference Issue (For mParticle employees only. Ignore if you are an outside contributor)

- Closes https://mparticle-eng.atlassian.net/browse/UNI-880

### CODE REVIEW

**Comment by ilyusha** [comment]
### Review Forge
[Click Here for AI Insights](https://supreme-adventure-m612l2p.pages.github.io?prUrl=https://github.com/mParticle/aquarium/pull/369)

**Review by tibuurcio — APPROVED** [review]
Talked with @nastyastavitskaya about this. Feels like the Minimap should live at a higher point in the component tree but this PR is only concerned with moving it from one place to another so we should address the refactoring later.

Approving it given ☝🏼

**Comment by nastyastavitskaya** [comment]
> ive at a higher point in the component tree

added ticket for that: https://mparticle-eng.atlassian.net/browse/UNI-917

**Comment by nastyastavitskaya** [comment]
> Talked with @nastyastavitskaya about this. Feels like the Minimap should live at a higher point in the component tree but this PR is only concerned with moving it from one place to another so we should address the refactoring later.
> 
> Approving it given ☝🏼

added a ticket for that: https://mparticle-eng.atlassian.net/browse/UNI-917

**Review by gabyzif — APPROVED** [review]
so exited about this

**Pull request merged**
